### ISSUE TITLE
sample balance

### ISSUE THREAD

**Issue by xiuliren** [nicholasturner1/PyTorchUtils#6]
it seems that you are not balancing the patch sample with and without cleft, is it correct?
https://github.com/nicholasturner1/PyTorchUtils/blob/master/materials/samplers/avan.py#L98

**Comment by nicholasturner1** [comment]
That's correct. That network always assumes that it's given a cleft object - it's not clear what would happen without giving it a cleft signal.

**Comment by xiuliren** [comment]
OK, it already works anyway. I thought you need to sample some empty patches to balance.
